language: php
sudo: false
php:
  - '5.6'
#  - '5.5'
#  - '5.4'
#matrix:
#  fast_finish: true
env:
  global:
    # Contains a $GITHUB_TOKEN env var for use with composer to avoid API limits.
    - secure: "WYBOW8/BG4/t9EQn5NWJ8k64v/H2fI15Z7tp6VwiqmD3Xlp+sG8TtHYIEnRJZFzVB+Mx9ghmgpf2fOMwPEY79dhHNcWwhLtgYn2rs9+FYSft4npauYS6dHttZOtDiyEIqmELGz0gnBpXA/X3ufMgtSplco2yz+LeC1TR7F3cYc4="
branches:
  except:
    - gh-pages
install:
  - composer self-update --no-interaction
  - composer config -g github-oauth.github.com $GITHUB_TOKEN
  - composer install --no-interaction
  - git clone https://github.com/loadsys/puphpet-release.git build/release-project
script:
  # Run unit tests.
  - vendor/bin/phpunit
  # Run integration tests.
  - tests/integration/simulate-composer-install.sh -t master
notifications:
  email: false
